server:
  host: 127.0.0.1
  port: 8080

log:
  level: debug
  filename: app.log
  max_age: 7
  max_backups: 3
  max_size: 100
  compress: true

database:
  # mysql, postgres, sqlite
  type: sqlite
  dsn: ./db.sqlite

security:
  jwt_secret: QQYnRFerJTSEcrfB89fw8prOaObmrch8
  jwt_expire: 3600