definitions:
  internal_handler.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  internal_handler.UserRegisterReq:
    properties:
      email:
        example: 1234@gmail.com
        type: string
      password:
        example: "123456"
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Example API
  version: 1.0.0
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UserRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler.Response'
      summary: 用户登录
      tags:
      - 用户模块
  /register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UserRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler.Response'
      summary: 用户注册
      tags:
      - 用户模块
  /users:
    get:
      consumes:
      - application/json
      description: 用户列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler.Response'
      summary: 用户列表
      tags:
      - 用户模块
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
