
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzIxMzE3NTQ3LCJuYmYiOjE3MjEzMTM5NDcsImlhdCI6MTcyMTMxMzk0N30.MmUmxfLyh-bh74aDmyJaIZFNEHDRBen9E75ywBH-YNs

### Login
POST /api/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

### Register
POST /api/register HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

### Get User
GET /api/users/11 HTTP/1.1
Host: localhost:8080
Authorization: Bearer {{token}}

### Create Menu
POST /api/menus HTTP/1.1
Host: localhost:8080
Authorization: Bearer {{token}}
Content-Type: application/json

# {
#     "name": "menu1",
#     "parent_id": 0,
#     "icon": "fa fa-home",
#     "url": "/home",
#     "sort": 1,
#     "enabled": 1
# }

# {
#     "name": "menu2",
#     "parent_id": 0,
#     "icon": "fa fa-home",
#     "url": "/home",
#     "sort": 2,
#     "enabled": 1
# }

{
    "name": "menu1-1",
    "parent_id": 1,
    "icon": "fa fa-home",
    "url": "/home",
    "sort": 1,
    "enabled": 1
}

### List Menus
GET /api/menus HTTP/1.1
Host: localhost:8080
Authorization: Bearer {{token}}

